In [7]:
import xarray as xr
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from datetime import datetime,timedelta
import warnings

In [8]:
path='/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/Surface Pressure-NCAR/*.nc'
data=xr.open_mfdataset(path)

In [9]:
data.pres


<xarray.DataArray 'pres' (time: 15340, lat: 73, lon: 144)>
dask.array<concatenate, shape=(15340, 73, 144), dtype=float32, chunksize=(366, 73, 144), chunktype=numpy.ndarray>
Coordinates:
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... -82.5 -85.0 -87.5 -90.0
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
  * time     (time) datetime64[ns] 1981-01-01 1981-01-02 ... 2022-12-31
Attributes:
    long_name:     mean Daily Pressure at surface
    units:         Pascals
    precision:     -1
    GRIB_id:       1
    GRIB_name:     PRES
    var_desc:      Pressure
    dataset:       NCEP Reanalysis Daily Averages
    level_desc:    Surface
    statistic:     Mean
    parent_stat:   Individual Obs
    actual_range:  [ 49540. 109450.]
    valid_range:   [ 40000. 115000.]

In [10]:
data.lat 

<xarray.DataArray 'lat' (lat: 73)>
array([ 90. ,  87.5,  85. ,  82.5,  80. ,  77.5,  75. ,  72.5,  70. ,  67.5,
        65. ,  62.5,  60. ,  57.5,  55. ,  52.5,  50. ,  47.5,  45. ,  42.5,
        40. ,  37.5,  35. ,  32.5,  30. ,  27.5,  25. ,  22.5,  20. ,  17.5,
        15. ,  12.5,  10. ,   7.5,   5. ,   2.5,   0. ,  -2.5,  -5. ,  -7.5,
       -10. , -12.5, -15. , -17.5, -20. , -22.5, -25. , -27.5, -30. , -32.5,
       -35. , -37.5, -40. , -42.5, -45. , -47.5, -50. , -52.5, -55. , -57.5,
       -60. , -62.5, -65. , -67.5, -70. , -72.5, -75. , -77.5, -80. , -82.5,
       -85. , -87.5, -90. ], dtype=float32)
Coordinates:
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... -82.5 -85.0 -87.5 -90.0
Attributes:
    units:          degrees_north
    actual_range:   [ 90. -90.]
    long_name:      Latitude
    standard_name:  latitude
    axis:           Y

In [11]:
# len(data.lon)

In [12]:
data.lon

<xarray.DataArray 'lon' (lon: 144)>
array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5,
        25. ,  27.5,  30. ,  32.5,  35. ,  37.5,  40. ,  42.5,  45. ,  47.5,
        50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,  67.5,  70. ,  72.5,
        75. ,  77.5,  80. ,  82.5,  85. ,  87.5,  90. ,  92.5,  95. ,  97.5,
       100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. , 122.5,
       125. , 127.5, 130. , 132.5, 135. , 137.5, 140. , 142.5, 145. , 147.5,
       150. , 152.5, 155. , 157.5, 160. , 162.5, 165. , 167.5, 170. , 172.5,
       175. , 177.5, 180. , 182.5, 185. , 187.5, 190. , 192.5, 195. , 197.5,
       200. , 202.5, 205. , 207.5, 210. , 212.5, 215. , 217.5, 220. , 222.5,
       225. , 227.5, 230. , 232.5, 235. , 237.5, 240. , 242.5, 245. , 247.5,
       250. , 252.5, 255. , 257.5, 260. , 262.5, 265. , 267.5, 270. , 272.5,
       275. , 277.5, 280. , 282.5, 285. , 287.5, 290. , 292.5, 295. , 297.5,
       300. , 302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. , 322.5,
       325. , 327.5, 330. , 332.5, 335. , 337.5, 340. , 342.5, 345. , 347.5,
       350. , 352.5, 355. , 357.5], dtype=float32)
Coordinates:
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
Attributes:
    units:          degrees_east
    long_name:      Longitude
    actual_range:   [  0.  357.5]
    standard_name:  longitude
    axis:           X

##### The size of this data is already in the form we want.

# Extracting data

In [13]:
lat_range = slice(29,18.0)  # take lat values in backwards directions.
lon_range = slice(85, 97)  # 88.0 degrees east to 92.7 degrees east

# Use the sel method to select data within the specified Bangladesh region
data_bangladesh = data.sel(lat=lat_range,lon=lon_range)

In [14]:
import pandas as pd
import xarray as xr
from tqdm.auto import tqdm# Import tqdm
warnings.filterwarnings('ignore')

# # Open your netCDF dataset
# ds = xr.open_dataset('your_dataset.nc')

# Define the chunk size
chunk_size = 500  # Adjust this based on your available memory

# Initialize an empty DataFrame to store the results
t2m_df = pd.DataFrame(columns=['time', 'lat', 'lon', 'Surface Pressure'])

# Calculate the number of chunks
num_chunks = len(data.time)

# Create a tqdm progress bar
for start in tqdm(range(0, num_chunks, chunk_size),desc='Main Loop'):
    end = start + chunk_size
    chunk = data_bangladesh.isel(time=slice(start, end))

    # Extract the data
    time = chunk.time.values
    lat = chunk.lat.values
    lon = chunk.lon.values
    pres = chunk.pres.values

    # Create a DataFrame for this chunk and append it to the main DataFrame
    chunk_df = pd.DataFrame({
        'time': time.repeat(len(lat) * len(lon)),
        'lat': np.tile(lat, len(time) * len(lon)),
        'lon': np.tile(lon, len(time) * len(lat)),
        'Surface Pressure': pres.ravel()
    })

    t2m_df = t2m_df.append(chunk_df, ignore_index=True)

# t2m_df now contains the concatenated data
t2m_df

Main Loop:   0%|          | 0/31 [00:00<?, ?it/s]

time   lat   lon  Surface Pressure
0      1981-01-01  27.5  85.0           80000.0
1      1981-01-01  25.0  87.5           72370.0
2      1981-01-01  22.5  90.0           71430.0
3      1981-01-01  20.0  92.5           78660.0
4      1981-01-01  27.5  95.0           86430.0
...           ...   ...   ...               ...
306795 2022-12-31  20.0  85.0          100435.0
306796 2022-12-31  27.5  87.5          102035.0
306797 2022-12-31  25.0  90.0          102087.5
306798 2022-12-31  22.5  92.5          100190.0
306799 2022-12-31  20.0  95.0           98232.5

[306800 rows x 4 columns]

In [ ]:
sanjid

# We won't take this data too.

as this data is from a different source.


In [2]:
path='/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/Surface Pressure/*.nc'
data=xr.open_mfdataset(path)


In [16]:
data.pres


<xarray.DataArray 'pres' (time: 15340, lat: 73, lon: 144)>
dask.array<concatenate, shape=(15340, 73, 144), dtype=float32, chunksize=(366, 73, 144), chunktype=numpy.ndarray>
Coordinates:
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... -82.5 -85.0 -87.5 -90.0
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
  * time     (time) datetime64[ns] 1981-01-01 1981-01-02 ... 2022-12-31
Attributes: (12/14)
    long_name:      Daily Pressure at Surface
    units:          Pascals
    precision:      -1
    GRIB_id:        1
    GRIB_name:      PRES
    var_desc:       Pressure
    ...             ...
    statistic:      Mean
    parent_stat:    Individual Obs
    standard_name:  pressure
    cell_methods:   time: mean (of 4 6-hourly values in one day)
    actual_range:   [ 48970. 105930.]
    valid_range:    [ 32000. 195000.]

In [4]:
data.lat

<xarray.DataArray 'lat' (lat: 73)>
array([ 90. ,  87.5,  85. ,  82.5,  80. ,  77.5,  75. ,  72.5,  70. ,  67.5,
        65. ,  62.5,  60. ,  57.5,  55. ,  52.5,  50. ,  47.5,  45. ,  42.5,
        40. ,  37.5,  35. ,  32.5,  30. ,  27.5,  25. ,  22.5,  20. ,  17.5,
        15. ,  12.5,  10. ,   7.5,   5. ,   2.5,   0. ,  -2.5,  -5. ,  -7.5,
       -10. , -12.5, -15. , -17.5, -20. , -22.5, -25. , -27.5, -30. , -32.5,
       -35. , -37.5, -40. , -42.5, -45. , -47.5, -50. , -52.5, -55. , -57.5,
       -60. , -62.5, -65. , -67.5, -70. , -72.5, -75. , -77.5, -80. , -82.5,
       -85. , -87.5, -90. ], dtype=float32)
Coordinates:
  * lat      (lat) float32 90.0 87.5 85.0 82.5 80.0 ... -82.5 -85.0 -87.5 -90.0
Attributes:
    units:               degrees_north
    actual_range:        [ 90. -90.]
    long_name:           Latitude
    standard_name:       latitude
    axis:                Y
    coordinate_defines:  point

In [5]:
data.lon

<xarray.DataArray 'lon' (lon: 144)>
array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5,  20. ,  22.5,
        25. ,  27.5,  30. ,  32.5,  35. ,  37.5,  40. ,  42.5,  45. ,  47.5,
        50. ,  52.5,  55. ,  57.5,  60. ,  62.5,  65. ,  67.5,  70. ,  72.5,
        75. ,  77.5,  80. ,  82.5,  85. ,  87.5,  90. ,  92.5,  95. ,  97.5,
       100. , 102.5, 105. , 107.5, 110. , 112.5, 115. , 117.5, 120. , 122.5,
       125. , 127.5, 130. , 132.5, 135. , 137.5, 140. , 142.5, 145. , 147.5,
       150. , 152.5, 155. , 157.5, 160. , 162.5, 165. , 167.5, 170. , 172.5,
       175. , 177.5, 180. , 182.5, 185. , 187.5, 190. , 192.5, 195. , 197.5,
       200. , 202.5, 205. , 207.5, 210. , 212.5, 215. , 217.5, 220. , 222.5,
       225. , 227.5, 230. , 232.5, 235. , 237.5, 240. , 242.5, 245. , 247.5,
       250. , 252.5, 255. , 257.5, 260. , 262.5, 265. , 267.5, 270. , 272.5,
       275. , 277.5, 280. , 282.5, 285. , 287.5, 290. , 292.5, 295. , 297.5,
       300. , 302.5, 305. , 307.5, 310. , 312.5, 315. , 317.5, 320. , 322.5,
       325. , 327.5, 330. , 332.5, 335. , 337.5, 340. , 342.5, 345. , 347.5,
       350. , 352.5, 355. , 357.5], dtype=float32)
Coordinates:
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
Attributes:
    units:               degrees_east
    long_name:           Longitude
    actual_range:        [  0.  357.5]
    standard_name:       longitude
    axis:                X
    coordinate_defines:  point

# Don't take this data.
Because it's forecast data.

In [6]:
path='/mnt/1A42C1DD42C1BE2F/MyProjects/ML_HEATWAVE/sp/*.nc'
data2=xr.open_mfdataset(path)

In [7]:
data2

<xarray.Dataset>
Dimensions:    (lat: 94, lon: 192, time: 15340, nbnds: 2)
Coordinates:
  * lat        (lat) float32 88.54 86.65 84.75 82.85 ... -84.75 -86.65 -88.54
  * lon        (lon) float32 0.0 1.875 3.75 5.625 ... 352.5 354.4 356.2 358.1
  * time       (time) datetime64[ns] 1981-01-01 1981-01-02 ... 2022-12-31
Dimensions without coordinates: nbnds
Data variables:
    time_bnds  (time, nbnds) datetime64[ns] dask.array<chunksize=(365, 2), meta=np.ndarray>
    pres       (time, lat, lon) float32 dask.array<chunksize=(365, 94, 192), meta=np.ndarray>
Attributes:
    Conventions:    CF-1.0
    title:          Daily NCEP/DOE Reanalysis 2
    comments:       Data is from \nNCEP/DOE AMIP-II Reanalysis (Reanalysis-2)...
    platform:       Model
    source:         NCEP/DOE AMIP-II Reanalysis (Reanalysis-2) Model
    institution:    National Centers for Environmental Prediction
    dataset_title:  NCEP-DOE AMIP-II Reanalysis
    References:     https://www.psl.noaa.gov/data/gridded/data.ncep.reanalysi...
    source_url:     http://www.cpc.ncep.noaa.gov/products/wesley/reanalysis2/
    history:        created 2002/03 by Hoop (netCDF2.3)\nConverted to chunked...

In [8]:
data2.pres

<xarray.DataArray 'pres' (time: 15340, lat: 94, lon: 192)>
dask.array<concatenate, shape=(15340, 94, 192), dtype=float32, chunksize=(366, 94, 192), chunktype=numpy.ndarray>
Coordinates:
  * lat      (lat) float32 88.54 86.65 84.75 82.85 ... -84.75 -86.65 -88.54
  * lon      (lon) float32 0.0 1.875 3.75 5.625 7.5 ... 352.5 354.4 356.2 358.1
  * time     (time) datetime64[ns] 1981-01-01 1981-01-02 ... 2022-12-31
Attributes: (12/14)
    long_name:      Daily Forecast of Surface Pressure
    units:          Pascals
    precision:      -1
    GRIB_id:        1
    GRIB_name:      PRES
    var_desc:       Pressure
    ...             ...
    statistic:      Mean
    parent_stat:    Individual Obs
    standard_name:  air_pressure
    cell_methods:   time: mean (of 4 6-hourly values in one day)
    actual_range:   [ 49350. 105960.]
    valid_range:    [ 32250. 122750.]

In [9]:
lat_range = slice(29,18.0)  # take lat values in backwards directions.
lon_range = slice(85, 97)  # 88.0 degrees east to 92.7 degrees east

# Use the sel method to select data within the specified Bangladesh region
data_bangladesh = data2.sel(lat=lat_range,lon=lon_range)

In [10]:
import pandas as pd
import xarray as xr
from tqdm.auto import tqdm# Import tqdm
warnings.filterwarnings('ignore')

# # Open your netCDF dataset
# ds = xr.open_dataset('your_dataset.nc')

# Define the chunk size
chunk_size = 500  # Adjust this based on your available memory

# Initialize an empty DataFrame to store the results
pres_df = pd.DataFrame(columns=['time', 'lat', 'lon', 'pressure'])

# Calculate the number of chunks
num_chunks = len(data.time)

# Create a tqdm progress bar
for start in tqdm(range(0, num_chunks, chunk_size),desc='Main Loop'):
    end = start + chunk_size
    chunk = data_bangladesh.isel(time=slice(start, end))

    # Extract the data
    time = chunk.time.values
    lat = chunk.lat.values
    lon = chunk.lon.values
    pres = chunk.pres.values

    # Create a DataFrame for this chunk and append it to the main DataFrame
    chunk_df = pd.DataFrame({
        'time': time.repeat(len(lat) * len(lon)),
        'lat': np.tile(lat, len(time) * len(lon)),
        'lon': np.tile(lon, len(time) * len(lat)),
        'pressure': pres.ravel()
    })

    pres_df = pres_df.append(chunk_df, ignore_index=True)

# t2m_df now contains the concatenated data
pres_df

Main Loop:   0%|          | 0/31 [00:00<?, ?it/s]

time        lat     lon   pressure
0      1981-01-01  27.618601  86.250   74290.00
1      1981-01-01  25.713900  88.125   72340.00
2      1981-01-01  23.809200  90.000   73090.00
3      1981-01-01  21.904400  91.875   75960.00
4      1981-01-01  19.999701  93.750   78780.00
...           ...        ...     ...        ...
552235 2022-12-31  25.713900  88.125  101988.25
552236 2022-12-31  23.809200  90.000  102025.25
552237 2022-12-31  21.904400  91.875  101526.50
552238 2022-12-31  19.999701  93.750  100627.25
552239 2022-12-31  18.094999  95.625   99077.25

[552240 rows x 4 columns]

In [11]:
lat_range = slice(29,18.0)  # take lat values in backwards directions.
lon_range = slice(85, 97)  # 88.0 degrees east to 92.7 degrees east

# Use the sel method to select data within the specified Bangladesh region
data_bangladesh = data.sel(lat=lat_range,lon=lon_range)

In [12]:
import pandas as pd
import xarray as xr
from tqdm.auto import tqdm# Import tqdm
warnings.filterwarnings('ignore')

# # Open your netCDF dataset
# ds = xr.open_dataset('your_dataset.nc')

# Define the chunk size
chunk_size = 500  # Adjust this based on your available memory

# Initialize an empty DataFrame to store the results
pres_df = pd.DataFrame(columns=['time', 'lat', 'lon', 'pressure'])

# Calculate the number of chunks
num_chunks = len(data.time)

# Create a tqdm progress bar
for start in tqdm(range(0, num_chunks, chunk_size),desc='Main Loop'):
    end = start + chunk_size
    chunk = data_bangladesh.isel(time=slice(start, end))

    # Extract the data
    time = chunk.time.values
    lat = chunk.lat.values
    lon = chunk.lon.values
    pres = chunk.pres.values

    # Create a DataFrame for this chunk and append it to the main DataFrame
    chunk_df = pd.DataFrame({
        'time': time.repeat(len(lat) * len(lon)),
        'lat': np.tile(lat, len(time) * len(lon)),
        'lon': np.tile(lon, len(time) * len(lat)),
        'pressure': pres.ravel()
    })

    pres_df = pres_df.append(chunk_df, ignore_index=True)

# t2m_df now contains the concatenated data
pres_df

Main Loop:   0%|          | 0/31 [00:00<?, ?it/s]

time   lat   lon  pressure
0      1981-01-01  27.5  85.0   78220.0
1      1981-01-01  25.0  87.5   73850.0
2      1981-01-01  22.5  90.0   74170.0
3      1981-01-01  20.0  92.5   78080.0
4      1981-01-01  27.5  95.0   79940.0
...           ...   ...   ...       ...
306795 2022-12-31  20.0  85.0   99057.5
306796 2022-12-31  27.5  87.5  101485.0
306797 2022-12-31  25.0  90.0  101950.0
306798 2022-12-31  22.5  92.5  100125.0
306799 2022-12-31  20.0  95.0   97350.0

[306800 rows x 4 columns]